### ISSUE TITLE
Attempts to Reinstall Card Driver once read

### ISSUE THREAD

**Issue by m8kwr** [islog/liblogicalaccess#114]
Have an issue when a card is read, after it has been read the card driver attempt to re-install again.

**Comment by Maxhy** [comment]
That's because of PC/SC changes since Windows 7. RFID cards are handled as regular smartcard and Windows try to install a CSP. You should disable the global policy or make some specific card ATR exception (this is what LibLogicalAccess installer do when you installer the COM layer for C# use, for main RFID chips technologies but not all).

See https://support.microsoft.com/en-us/kb/976832
