### ISSUE TITLE
liblogicalaccess and motion detection?

### ISSUE THREAD

**Issue by ZuzooVn** [islog/liblogicalaccess#91]
Can liblogicalaccess Detecte Object Motion Using Passive RFID?

**Comment by Maxhy** [comment]
This is a question a bit too general :smile:.
But passive RFID give generally something like few cm distance, what would be the point of object motion detection on few cm here? Antitheft?
Otherwise liblogicalaccess doesn't have any motion detection behavior nop, never had the requirement and I don't think the technology would be 100% accurate for this use case.
